pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                cleanWs()
                echo 'Starts building of project'
                sh 'dotnet restore Relay/Relay.csproj'
                sh 'dotnet build Relay/Relay.csproj -c Release -o Relay/Build'
                sh 'dotnet publish Relay/Relay.csproj -c Release -o Relay/Output'
            }
        }
        stage('Archive Artifects'){
            steps{
                archiveArtifacts artifacts: '**/*', followSymlinks: false, onlyIfSuccessful: true
            }
        }
        stage('Deploy'){
            steps{
                ftpPublisher alwaysPublishFromMaster: false, 
                continueOnError: false, 
                failOnError: false, 
                masterNodeName: '',
                paramPublish: null,
                publishers: [[configName: 'localtest', transfers: [[asciiMode: false, cleanRemote: false, excludes: '', flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '', remoteDirectorySDF: false, removePrefix: '', sourceFiles: '**/*']], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false]]
            }

        }
    }
}