pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                echo 'Starts building of project'
                sh 'dotnet restore Relay/Relay.csproj'
                sh 'dotnet publish Relay/Relay.csproj -c Release -o Relay/Output'
            }
            post{
                success{
                    echo 'archiving artifacts...'
                    archiveArtifacts artifacts: '**/*'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps {
                build job: 'Deploy_to_production'

            }
            
        }
    }
}